# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.1"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Linting
      run: |
        pip install "black<23" pylint==v3.0.0a3 mypy==v0.902
        black --diff --check $(git ls-files '*.py')
        pylint --disable=all --enable=unused-import $(git ls-files '*.py')
        mypy --strict $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        python -m unittest tests/*.py
